<a href="https://colab.research.google.com/github/Chirag314/Huggingface/blob/main/Huggingface_models_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers
!pip install torch

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinu

In [2]:
import torch
from transformers import pipeline


In [4]:
# Import the function for loading Hugging Face pipelines
from transformers import pipeline

review = "The food was good, but service at the restaurant was a bit slow"

# Load the pipeline for text classification
classifier = pipeline(task="text-classification", model="nlptown/bert-base-multilingual-uncased-sentiment")

# Pass the customer review to the model for prediction
prediction =classifier(review)
print(prediction)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/953 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/669M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/872k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

[{'label': '3 stars', 'score': 0.6387940049171448}]


In [5]:
# Load the model pipeline for text summarization
summarizer = pipeline(task="summarization", model="facebook/bart-large-cnn")

# Pass the long text to the model to summarize it
long_text="""Walking amid Gion's Machiya wooden houses is a mesmerizing experience. The beautifully preserved structures exuded an old-world charm that transports visitors back in time, making them feellike they had stepped into a living museum. The glow of lanterns lining the narrow streets add to theenchanting ambiance, making each stroll a memorable journey through Japan's rich cultural history."""


outputs = summarizer(long_text,max_length=50,clean_up_tokenization_spaces=True )

# Access and print the summarized text in the outputs variable
print(outputs[0]['summary_text'])

config.json:   0%|          | 0.00/1.58k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Your min_length=56 must be inferior than your max_length=50.
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1273: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (50). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length.
  warnings.warn(


Gion's Machiya wooden houses exuded an old-world charm that transports visitors back in time. The glow of lanterns lining the narrow streets add to theenchanting ambiance, making each stroll a memorable journey through Japan


In [6]:
# Load the model pipeline for question-answering
qa_model = pipeline("question-answering")
question = "For how long was the Eiffel Tower the tallest man-made structure in the world?"
context="The Eiffel Tower is a wrought iron tower in Paris, France that is 330 meters (1,083 ft) tall and is the city's tallest structure. It was built in 1889 for the Exposition Universelle, a world fair celebrating the 100th anniversary of the French Revolution. When it opened, it was the world's tallest building, a title it held for 41 years. The tower is made up of 18,000 iron pieces and over 2.5 million rivets, and has 1,665 stairs and three viewing platforms"
# Pass the inputs to the pipeline
outputs = qa_model(question=question, context=context)

# Access and print the answer
print(outputs['answer'])

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 626af31 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/261M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

41 years


In [ ]:
translator=pipeline(task="translation",
                    model="facebook/nllb-200-distilled-600M",
                    torch_dtype=torch.bfloat16
                    )

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/846 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/564 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/4.85M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.3M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/3.55k [00:00<?, ?B/s]

In [ ]:
text="""\
My puppy is adorable, \
Your kitten s cute.
Her panda is friendly.
His llama is thoughful.\
We all have nice pets!"""

In [ ]:
text_translated=translator(text,
                          src_lang="eng_Latn",
                          tgt_lang="fra_Latn")


In [ ]:
text_translated

[{'translation_text': 'Mon chiot est adorable, ton chaton est mignon, son panda est ami, sa lamme est pleine de pensée, nous avons tous de beaux animaux de compagnie.'}]

In [ ]:
import gc
del translator
gc.collect()

108

In [ ]:
summarizer=pipeline(task="summarization",
                    model="facebook/bart-large-cnn",
                    torch_dtype=torch.bfloat16)

config.json:   0%|          | 0.00/1.58k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [ ]:
text="""
Accomplished Lead Statistical Programmer with a passion for delivering valuable data through statistical
and data retrieval methodologies. Over 10 years of experience including clinical trial data analysis in
 Oncology, Women’s health, Infectious disease, Blood Pressure and Diabetes related therapeutic areas.
 Highly skilled in data analysis, data visualization with hands on knowledge of machine learning/deep
 learning. Seeking to learn new ML skills and applying knowledge to dynamic, growth-oriented role.
 Working as Lead-Statistical Programmer in multiple phases of clinical trials for women’s health related
  therapeutic area. Leading a team of 9 junior and senior programmers.
"""

In [ ]:
summary=summarizer(text,
                   min_length=10,
                   max_length=100
                   )

In [ ]:
summary

[{'summary_text': 'Leading data analyst with over 10 years of experience. Has worked in a range of fields including health care, finance, business and education.'}]

In [ ]:
!pip install sentence-transformers

In [ ]:
from transformers.utils import logging
logging.set_verbosity_error()

In [ ]:
from sentence_transformers import SentenceTransformer, util

In [ ]:
model=SentenceTransformer("all-MiniLM-L6-v2")

In [ ]:
sentences1=['the cat sits outside',
            ' A man is playing guitar',
            'the movies are awesome']
sentences2=['The dog plays in the garden',
            'A woman is watching TV',
            'The new movie is so great']

In [ ]:
embeddings1=model.encode(sentences1,
                         convert_to_tensor=True)
embeddings2=model.encode(sentences2,
                         convert_to_tensor=True)

In [ ]:
print(embeddings1)

tensor([[ 0.1392,  0.0030,  0.0470,  ...,  0.0641, -0.0163,  0.0636],
        [ 0.0227, -0.0014, -0.0056,  ..., -0.0225,  0.0846, -0.0283],
        [-0.1043, -0.0628,  0.0093,  ...,  0.0020,  0.0653, -0.0150]])


In [ ]:
print(embeddings2)

tensor([[ 0.0163, -0.0700,  0.0384,  ...,  0.0447,  0.0254, -0.0023],
        [-0.0043, -0.0883,  0.0014,  ...,  0.0394,  0.0058, -0.0670],
        [-0.0842, -0.0592, -0.0010,  ..., -0.0157,  0.0764,  0.0389]])


In [ ]:
cosine_scores=util.cos_sim(embeddings1,embeddings2)
print(cosine_scores)

tensor([[ 0.2838,  0.1189, -0.0029],
        [ 0.2277, -0.0077, -0.0136],
        [-0.0124, -0.0631,  0.6571]])


In [ ]:
for i in range(len(sentences1)):
  print("{}\t\t {} Score: {:.4f}".format(sentences1[i],sentences2[i],cosine_scores[i][i]))

the cat sits outside		 The dog plays in the garden Score: 0.2838
 A man is playing guitar		 A woman is watching TV Score: -0.0077
the movies are awesome		 The new movie is so great Score: 0.6571


### Zero -shot audio classification

In [ ]:
!pip install datasets
!pip install soundfile
!pip install librosa


In [ ]:
from datasets import load_dataset, DatasetDict,load_from_disk
from transformers import pipeline
dataset=load_from_disk("./models/ashraq/esc50/train")

FileNotFoundError: Directory ./models/ashraq/esc50/train not found

In [ ]:
audio_sample=dataset[0]