<a href="https://colab.research.google.com/github/Chirag314/Huggingface/blob/main/Huggingface_models_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers
!pip install torch

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinu

In [ ]:
import torch
from transformers import pipeline


In [ ]:
translator=pipeline(task="translation",
                    model="facebook/nllb-200-distilled-600M",
                    torch_dtype=torch.bfloat16
                    )

config.json:   0%|          | 0.00/846 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/564 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/4.85M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.3M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/3.55k [00:00<?, ?B/s]

In [ ]:
text="""\
My puppy is adorable, \
Your kitten s cute.
Her panda is friendly.
His llama is thoughful.\
We all have nice pets!"""

In [ ]:
text_translated=translator(text,
                          src_lang="eng_Latn",
                          tgt_lang="fra_Latn")


In [ ]:
text_translated

[{'translation_text': 'Mon chiot est adorable, ton chaton est mignon, son panda est ami, sa lamme est pleine de pensée, nous avons tous de beaux animaux de compagnie.'}]

In [ ]:
import gc
del translator
gc.collect()

336

In [ ]:
summarizer=pipeline(task="summarization",
                    model="facebook/bart-large-cnn",
                    torch_dtype=torch.bfloat16)

config.json:   0%|          | 0.00/1.58k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [ ]:
text="""
Accomplished Lead Statistical Programmer with a passion for delivering valuable data through statistical
and data retrieval methodologies. Over 10 years of experience including clinical trial data analysis in
 Oncology, Women’s health, Infectious disease, Blood Pressure and Diabetes related therapeutic areas.
 Highly skilled in data analysis, data visualization with hands on knowledge of machine learning/deep
 learning. Seeking to learn new ML skills and applying knowledge to dynamic, growth-oriented role.
 Working as Lead-Statistical Programmer in multiple phases of clinical trials for women’s health related
  therapeutic area. Leading a team of 9 junior and senior programmers.
"""

In [ ]:
summary=summarizer(text,
                   min_length=10,
                   max_length=100
                   )

In [ ]:
summary

[{'summary_text': 'Accomplished Lead Statistical Programmer with a passion for delivering valuable data through statistical and data retrieval methodologies. Over 10 years of experience including clinical trial data analysis.'}]

In [2]:
!pip install sentence-transformers

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinu

In [1]:
from transformers.utils import logging
logging.set_verbosity_error()

In [5]:
from sentence_transformers import SentenceTransformer, util

In [6]:
model=SentenceTransformer("all-MiniLM-L6-v2")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [7]:
sentences1=['the cat sits outside',
            ' A man is playing guitar',
            'the movies are awesome']
sentences2=['The dog plays in the garden',
            'A woman is watching TV',
            'The new movie is so great']

In [8]:
embeddings1=model.encode(sentences1,
                         convert_to_tensor=True)
embeddings2=model.encode(sentences2,
                         convert_to_tensor=True)

In [9]:
print(embeddings1)

tensor([[ 0.1392,  0.0030,  0.0470,  ...,  0.0641, -0.0163,  0.0636],
        [ 0.0227, -0.0014, -0.0056,  ..., -0.0225,  0.0846, -0.0283],
        [-0.1043, -0.0628,  0.0093,  ...,  0.0020,  0.0653, -0.0150]])


In [10]:
print(embeddings2)

tensor([[ 0.0163, -0.0700,  0.0384,  ...,  0.0447,  0.0254, -0.0023],
        [-0.0043, -0.0883,  0.0014,  ...,  0.0394,  0.0058, -0.0670],
        [-0.0842, -0.0592, -0.0010,  ..., -0.0157,  0.0764,  0.0389]])


In [11]:
cosine_scores=util.cos_sim(embeddings1,embeddings2)
print(cosine_scores)

tensor([[ 0.2838,  0.1189, -0.0029],
        [ 0.2277, -0.0077, -0.0136],
        [-0.0124, -0.0631,  0.6571]])


In [12]:
for i in range(len(sentences1)):
  print("{}\t\t {} Score: {:.4f}".format(sentences1[i],sentences2[i],cosine_scores[i][i]))

the cat sits outside		 The dog plays in the garden Score: 0.2838
 A man is playing guitar		 A woman is watching TV Score: -0.0077
the movies are awesome		 The new movie is so great Score: 0.6571
